UPDATE items
SET seller_id = null;

UPDATE items
SET buyer_id = null;

UPDATE bids
SET user_id = null;

DELETE FROM items;

DELETE FROM users;

DELETE FROM bids;

ALTER TABLE ITEMS
    ALTER COLUMN id RESTART WITH 1;

ALTER TABLE USERS
    ALTER COLUMN id RESTART WITH 1;

ALTER TABLE BIDS
    ALTER COLUMN id RESTART WITH 1;