CREATE TABLE USERS
(
    ID                BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    USERNAME          VARCHAR(45) NOT NULL UNIQUE,
    PASSWORD          VARCHAR(90) NOT NULL,
    GREEN_BAY_DOLLARS BIGINT
);

CREATE TABLE ITEMS
(
    ID             BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NAME           VARCHAR(45),
    DESCRIPTION    VARCHAR(250),
    PHOTO_URL      VARCHAR(90),
    STARTING_PRICE INT,
    PURCHASE_PRICE INT,
    SOLD           SMALLINT,
    BUYER_ID       BIGINT,
    SELLER_ID       BIGINT
);

CREATE TABLE BIDS
(
    ID        BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    BID_VALUE BIGINT,
    ITEM_ID   BIGINT,
    USER_ID   BIGINT
);

ALTER TABLE ITEMS
    ADD FOREIGN KEY (SELLER_ID) REFERENCES USERS (ID);

ALTER TABLE ITEMS
    ADD FOREIGN KEY (BUYER_ID) REFERENCES USERS (ID);